#!/usr/bin/env bash
CONFIG_DIR="$HOME/.config/lite-xl"

echo "Uninstalling Lite-XL Mossy Configuration..."

rm -f "$CONFIG_DIR/plugins/antigravity_sidebar.lua"
rm -f "$CONFIG_DIR/plugins/mossy_icons.lua"
rm -f "$CONFIG_DIR/plugins/mossy_treeview.lua"
rm -f "$CONFIG_DIR/plugins/toggle_terminal.lua"
rm -f "$CONFIG_DIR/plugins/mossy_statusbar.lua"
rm -f "$CONFIG_DIR/plugins/autoclose.lua"
rm -f "$CONFIG_DIR/plugins/auto_healer.lua"
rm -f "$CONFIG_DIR/plugins/git_timeline.lua"
rm -f "$CONFIG_DIR/plugins/github_codespaces.lua"
rm -f "$CONFIG_DIR/plugins/language_ignore.lua"
rm -f "$CONFIG_DIR/plugins/resource_monitor.lua"
rm -f "$CONFIG_DIR/plugins/tempfiles_manager.lua"
rm -f "$CONFIG_DIR/plugins/progress_pet.lua"
rm -f "$CONFIG_DIR/plugins/virtual_codespace_fs.lua"
rm -f "$CONFIG_DIR/plugins/codespace_treeview.lua"
rm -f "$CONFIG_DIR/plugins/agy_pty_bridge.py"
rm -f "$CONFIG_DIR/colors/everforest_lite_xl.lua"
rm -f "$CONFIG_DIR/colors/dark_forest_lite_xl.lua"
rm -f "$CONFIG_DIR/colors/tokyo_night_remix.lua"
rm -f "$CONFIG_DIR/fonts/FiraCode-iScript.ttf"
rm -f "$CONFIG_DIR/fonts/FiraCodeiScript-Bold.ttf"
rm -f "$CONFIG_DIR/fonts/FiraCodeNerdFont-Regular.ttf"
rm -f "$CONFIG_DIR/scripts/remote_lsp_proxy.py"
rm -rf "$CONFIG_DIR/plugins/lsp"
rm -rf "$CONFIG_DIR/plugins/widget"
rm -rf "$CONFIG_DIR/codespaces"

echo "Removed plugin, color, and font files."
echo ""
echo "IMPORTANT: Please manually open $CONFIG_DIR/init.lua"
echo "and delete the lines under '-- [[ LazyLite Configuration ]]'"
echo ""
echo "Uninstallation complete! Restart Lite-XL."
