-- mod-version:3
-- splash_art.lua  –  Rich ASCII art for the empty view & terminal startup.
-- Auto-generated by scripts/gen_splash_art.py — re-run to regenerate with a different style.

local core   = require "core"
local style  = require "core.style"
local keymap = require "core.keymap"

-- ── Art ───────────────────────────────────────────────────────────────────────

local SPLASH_ART = [==[
  .-------------------------------------------------------------------.
  |                                                                   |
  |  '##:::::::'####:'########:'########:::::::'##::::'##:'##:::::::  |
  |   ##:::::::. ##::... ##..:: ##.....::::::::. ##::'##:: ##:::::::  |
  |   ##:::::::: ##::::: ##:::: ##::::::::::::::. ##'##::: ##:::::::  |
  |   ##:::::::: ##::::: ##:::: ######:::::::::::. ###:::: ##:::::::  |
  |   ##:::::::: ##::::: ##:::: ##...:::::::::::: ## ##::: ##:::::::  |
  |   ##:::::::: ##::::: ##:::: ##:::::::::::::: ##:. ##:: ##:::::::  |
  |   ########:'####:::: ##:::: ########::::::: ##:::. ##: ########:  |
  |  ........::....:::::..:::::........::::::::..:::::..::........::  |
  |                                                                   |
  '-------------------------------------------------------------------'

                       The Lightweight Text Editor
]==]

local TERMINAL_BANNER = [==[

  ╔═════════════════════════════════════════════════════════════════════╗
  ║                                                                     ║
  ║   '##:::::::'####:'########:'########:::::::'##::::'##:'##:::::::   ║
  ║    ##:::::::. ##::... ##..:: ##.....::::::::. ##::'##:: ##:::::::   ║
  ║    ##:::::::: ##::::: ##:::: ##::::::::::::::. ##'##::: ##:::::::   ║
  ║    ##:::::::: ##::::: ##:::: ######:::::::::::. ###:::: ##:::::::   ║
  ║    ##:::::::: ##::::: ##:::: ##...:::::::::::: ## ##::: ##:::::::   ║
  ║    ##:::::::: ##::::: ##:::: ##:::::::::::::: ##:. ##:: ##:::::::   ║
  ║    ########:'####:::: ##:::: ########::::::: ##:::. ##: ########:   ║
  ║   ........::....:::::..:::::........::::::::..:::::..::........::   ║
  ║                                                                     ║
  ╠═════════════════════════════════════════════════════════════════════╣
  ║        The lightweight text editor — fast, beautiful, yours.        ║
  ║                  v2.1.8   ·   https://lite-xl.com                   ║
  ╚═════════════════════════════════════════════════════════════════════╝

]==]

-- ── Helpers ───────────────────────────────────────────────────────────────────

local function split_lines(s)
  local t = {}
  for l in (s .. "\n"):gmatch("([^\n]*)\n") do
    table.insert(t, (l:gsub("\r", "")))
  end
  while #t > 0 and t[#t]:match("^%s*$") do table.remove(t) end
  while #t > 0 and t[1] :match("^%s*$") do table.remove(t, 1) end
  return t
end

-- ── Override EmptyView.draw ───────────────────────────────────────────────────

local EmptyView = require "core.emptyview"
EmptyView.draw = function(self)
  self:draw_background(style.background)

  local sf  = style.code_font or style.font  -- monospace for art
  local lf  = style.font                      -- proportional for hints
  local dim = style.dim

  local bg = style.background
  local is_light = (bg[1] * 0.299 + bg[2] * 0.587 + bg[3] * 0.114) > 128

  -- Derive a bold/bright foreground from style.accent
  local acc = style.accent or { 120, 200, 255, 255 }
  local bright = { acc[1], acc[2], acc[3], 240 }

  -- Shadow color: softer on light themes, deeper on dark themes
  local shadow = is_light and { 0, 0, 0, 50 } or { 0, 0, 0, 150 }

  -- Shadow offset and bold thickness
  local sh = math.ceil(2 * SCALE)
  local bold_off = math.max(1, math.ceil(1 * SCALE))

  local art_lines = split_lines(SPLASH_ART)

  -- Line height: slightly tighter for dense block art
  local fh    = math.floor(sf:get_height() * 1.05)
  local art_h = #art_lines * fh

  -- Hint lines
  local hints = {
    { fmt = "%s   run a command",            cmd = "core:find-command" },
    { fmt = "%s   open a file from project", cmd = "core:find-file" },
    { fmt = "%s   change project folder",    cmd = "core:change-project-folder" },
    { fmt = "%s   open a project folder",    cmd = "core:open-project-folder" },
  }
  local hfh     = lf:get_height() + 6
  local hints_h = #hints * hfh + 24

  local total_h = art_h + 24 + hints_h
  local start_y = self.position.y + math.max(style.padding.y, (self.size.y - total_h) / 2)

  -- Measure art width for centering
  local max_art_w = 0
  for _, l in ipairs(art_lines) do
    local w = sf:get_width(l)
    if w > max_art_w then max_art_w = w end
  end
  local art_x = self.position.x + math.max(style.padding.x, (self.size.x - max_art_w) / 2)

  -- Draw ASCII logo — shadow pass first, then bright text on top, drawn twice to simulate bold weight
  local cy = start_y
  for _, l in ipairs(art_lines) do
    -- Shadow (offset down-right, doubled for bold)
    renderer.draw_text(sf, l, art_x + sh, cy + sh, shadow)
    renderer.draw_text(sf, l, art_x + sh + bold_off, cy + sh, shadow)
    -- Bright foreground (doubled for bold)
    renderer.draw_text(sf, l, art_x, cy, bright)
    renderer.draw_text(sf, l, art_x + bold_off, cy, bright)
    cy = cy + fh
  end


  cy = cy + 12

  -- Thin divider
  local div_alpha = { dim[1], dim[2], dim[3], 30 }
  local div_w = self.size.x - style.padding.x * 4
  local div_x = self.position.x + style.padding.x * 2
  renderer.draw_rect(div_x, math.floor(cy), div_w, math.ceil(SCALE), div_alpha)
  cy = cy + 12

  -- Hint lines
  local max_hint_w = 0
  for _, h in ipairs(hints) do
    local binding = keymap.get_binding(h.cmd) or "?"
    local txt = string.format(h.fmt, binding)
    local w = lf:get_width(txt)
    if w > max_hint_w then max_hint_w = w end
  end
  local hx = self.position.x + math.max(style.padding.x, (self.size.x - max_hint_w) / 2)

  for _, h in ipairs(hints) do
    local binding = keymap.get_binding(h.cmd) or "?"
    local txt = string.format(h.fmt, binding)
    renderer.draw_text(lf, txt, hx, cy, dim)
    cy = cy + hfh
  end
end

-- ── Terminal banner on startup ────────────────────────────────────────────────

local _banner_done = false
core.add_thread(function()
  coroutine.yield(1.0)
  if _banner_done then return end
  local function walk(node)
    if not node then return end
    if node.views then
      for _, v in ipairs(node.views) do
        if v.terminal and v.terminal.write then
          v.terminal:write(TERMINAL_BANNER)
          _banner_done = true
        end
      end
    end
    if node.a then walk(node.a) end
    if node.b then walk(node.b) end
  end
  pcall(walk, core.root_view and core.root_view.root_node)
end)
