-- mod-version:3
-- splash_art.lua  –  Rich ASCII art for the empty view & terminal startup.
-- Auto-generated by scripts/gen_splash_art.py — re-run to regenerate with a different style.

local core   = require "core"
local style  = require "core.style"
local keymap = require "core.keymap"

-- ── Art ───────────────────────────────────────────────────────────────────────

local SPLASH_ART = [==[
  .-------------------------------------------------------------------.
  |                                                                   |
  |  '##:::::::'####:'########:'########:::::::'##::::'##:'##:::::::  |
  |   ##:::::::. ##::... ##..:: ##.....::::::::. ##::'##:: ##:::::::  |
  |   ##:::::::: ##::::: ##:::: ##::::::::::::::. ##'##::: ##:::::::  |
  |   ##:::::::: ##::::: ##:::: ######:::::::::::. ###:::: ##:::::::  |
  |   ##:::::::: ##::::: ##:::: ##...:::::::::::: ## ##::: ##:::::::  |
  |   ##:::::::: ##::::: ##:::: ##:::::::::::::: ##:. ##:: ##:::::::  |
  |   ########:'####:::: ##:::: ########::::::: ##:::. ##: ########:  |
  |  ........::....:::::..:::::........::::::::..:::::..::........::  |
  |                                                                   |
  '-------------------------------------------------------------------'

                       The Lightweight Text Editor
]==]

local TERMINAL_BANNER = [==[

  ╔═════════════════════════════════════════════════════════════════════╗
  ║                                                                     ║
  ║   '##:::::::'####:'########:'########:::::::'##::::'##:'##:::::::   ║
  ║    ##:::::::. ##::... ##..:: ##.....::::::::. ##::'##:: ##:::::::   ║
  ║    ##:::::::: ##::::: ##:::: ##::::::::::::::. ##'##::: ##:::::::   ║
  ║    ##:::::::: ##::::: ##:::: ######:::::::::::. ###:::: ##:::::::   ║
  ║    ##:::::::: ##::::: ##:::: ##...:::::::::::: ## ##::: ##:::::::   ║
  ║    ##:::::::: ##::::: ##:::: ##:::::::::::::: ##:. ##:: ##:::::::   ║
  ║    ########:'####:::: ##:::: ########::::::: ##:::. ##: ########:   ║
  ║   ........::....:::::..:::::........::::::::..:::::..::........::   ║
  ║                                                                     ║
  ╠═════════════════════════════════════════════════════════════════════╣
  ║        The lightweight text editor — fast, beautiful, yours.        ║
  ║                  v2.1.8   ·   https://lite-xl.com                   ║
  ╚═════════════════════════════════════════════════════════════════════╝

]==]

-- ── Helpers ───────────────────────────────────────────────────────────────────

local function split_lines(s)
  local t = {}
  for l in (s .. "\n"):gmatch("([^\n]*)\n") do
    table.insert(t, (l:gsub("\r", "")))
  end
  while #t > 0 and t[#t]:match("^%s*$") do table.remove(t) end
  while #t > 0 and t[1] :match("^%s*$") do table.remove(t, 1) end
  return t
end

-- ── Override EmptyView.draw ───────────────────────────────────────────────────

local EmptyView = require "core.emptyview"
EmptyView.draw = function(self)
  self:draw_background(style.background)

  local sf  = style.code_font or style.font  -- monospace for art
  local lf  = style.font                      -- proportional for hints
  local dim = style.dim

  local art_lines = split_lines(SPLASH_ART)

  -- Line height: slightly tighter for dense block art
  local fh    = math.floor(sf:get_height() * 1.05)
  local art_h = #art_lines * fh

  -- Hint lines
  local hints = {
    { fmt = "%s   run a command",            cmd = "core:find-command" },
    { fmt = "%s   open a file from project", cmd = "core:find-file" },
    { fmt = "%s   change project folder",    cmd = "core:change-project-folder" },
    { fmt = "%s   open a project folder",    cmd = "core:open-project-folder" },
  }
  local hfh     = lf:get_height() + 6
  local hints_h = #hints * hfh + 24

  local total_h = art_h + 24 + hints_h
  local start_y = self.position.y + math.max(style.padding.y, (self.size.y - total_h) / 2)

  -- Measure art width for centering
  local max_art_w = 0
  for _, l in ipairs(art_lines) do
    local w = sf:get_width(l)
    if w > max_art_w then max_art_w = w end
  end
  local art_x = self.position.x + math.max(style.padding.x, (self.size.x - max_art_w) / 2)

  -- Draw ASCII logo
  local cy = start_y
  for i, l in ipairs(art_lines) do
    -- Banner line (first line) gets a slightly brighter tint
    local col = (i == 1) and { dim[1], dim[2], dim[3], math.floor((dim[4] or 255) * 0.7) } or dim
    renderer.draw_text(sf, l, art_x, cy, col)
    cy = cy + fh
  end

  cy = cy + 12

  -- Thin divider
  local div_alpha = { dim[1], dim[2], dim[3], 30 }
  local div_w = self.size.x - style.padding.x * 4
  local div_x = self.position.x + style.padding.x * 2
  renderer.draw_rect(div_x, math.floor(cy), div_w, math.ceil(SCALE), div_alpha)
  cy = cy + 12

  -- Hint lines
  local max_hint_w = 0
  for _, h in ipairs(hints) do
    local binding = keymap.get_binding(h.cmd) or "?"
    local txt = string.format(h.fmt, binding)
    local w = lf:get_width(txt)
    if w > max_hint_w then max_hint_w = w end
  end
  local hx = self.position.x + math.max(style.padding.x, (self.size.x - max_hint_w) / 2)

  for _, h in ipairs(hints) do
    local binding = keymap.get_binding(h.cmd) or "?"
    local txt = string.format(h.fmt, binding)
    renderer.draw_text(lf, txt, hx, cy, dim)
    cy = cy + hfh
  end
end

-- ── Terminal banner on startup ────────────────────────────────────────────────

local _banner_done = false
core.add_thread(function()
  coroutine.yield(1.0)
  if _banner_done then return end
  local function walk(node)
    if not node then return end
    if node.views then
      for _, v in ipairs(node.views) do
        if v.terminal and v.terminal.write then
          v.terminal:write(TERMINAL_BANNER)
          _banner_done = true
        end
      end
    end
    if node.a then walk(node.a) end
    if node.b then walk(node.b) end
  end
  pcall(walk, core.root_view and core.root_view.root_node)
end)
