#!/usr/bin/env python3
"""
gen_splash_art.py
Generates rich ASCII art for Lite XL's empty view and terminal splash screen.
  - Empty view  : "Electronic" font  (▄ ▐░▌ half-block style)
  - Terminal    : "banner3-D" font   (##:::::: dot-grid style)
Uses pyfiglet for art generation. Re-run any time to regenerate.
"""

import pyfiglet
import os
import sys
import io

# Force UTF-8 output so box chars don't explode on Windows console
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

USERDIR  = os.path.join(os.path.expanduser("~"), ".config", "lite-xl")
OUT_LUA  = os.path.join(USERDIR, "plugins", "splash_art.lua")

# ── Art generation ─────────────────────────────────────────────────────────────

def trim(lines):
    while lines and not lines[0].strip():  lines.pop(0)
    while lines and not lines[-1].strip(): lines.pop()
    return lines

def art(text, font):
    raw   = pyfiglet.figlet_format(text, font=font)
    return trim([l.rstrip() for l in raw.splitlines()])


def make_splash():
    """
    Compact rich logo for the empty editor view.
    Uses banner3-D (8 lines) — same dot-grid style, perfectly sized.
    Wrapped in a light ASCII frame for a premium look.
    """
    lines = art("Lite  XL", "banner3-D")
    width = max(len(l) for l in lines)

    # Box frame
    top  = "  ." + "-" * (width + 4) + "."
    bot  = "  '" + "-" * (width + 4) + "'"
    sep  = "  |" + " " * (width + 4) + "|"

    framed = [top, sep]
    for l in lines:
        framed.append("  |  " + l.ljust(width) + "  |")
    framed.append(sep)
    framed.append(bot)

    # Tagline beneath the box
    tagline  = "The Lightweight Text Editor"
    tag_pad  = (width + 6 - len(tagline)) // 2
    framed.append("")
    framed.append(" " * (tag_pad + 2) + tagline)
    return "\n".join(framed)


def make_terminal_banner():
    """
    Sharp banner3-D logo for the terminal startup.
    Adds double-line borders and a tagline.
    """
    lines = art("Lite  XL", "banner3-D")
    width = max(len(l) for l in lines)

    inner_w = width + 6
    top    = "  " + "╔" + "═" * inner_w + "╗"
    bot    = "  " + "╚" + "═" * inner_w + "╝"
    div    = "  " + "╠" + "═" * inner_w + "╣"
    blank  = "  " + "║" + " " * inner_w + "║"
    sep    = "  " + "║" + "─" * inner_w + "║"

    def row(line):
        padded = "   " + line.ljust(width) + "   "
        return "  ║" + padded + "║"

    tagline   = f"   {'The lightweight text editor — fast, beautiful, yours.':^{inner_w}}   "
    tag_row   = "  ║" + f"{'  The lightweight text editor — fast, beautiful, yours.  ':^{inner_w}}" + "║"
    ver_row   = "  ║" + f"{'  v2.1.8   ·   https://lite-xl.com  ':^{inner_w}}" + "║"

    result = ["", top, blank]
    for l in lines:
        result.append(row(l))
    result.append(blank)
    result.append(div)
    result.append(tag_row)
    result.append(ver_row)
    result.append(bot)
    result.append("")
    return "\n".join(result)


SPLASH_ART      = make_splash()
TERMINAL_BANNER = make_terminal_banner()

# ── Lua plugin ─────────────────────────────────────────────────────────────────

LUA = r"""-- mod-version:3
-- splash_art.lua  –  Rich ASCII art for the empty view & terminal startup.
-- Auto-generated by scripts/gen_splash_art.py — re-run to regenerate with a different style.

local core   = require "core"
local style  = require "core.style"
local keymap = require "core.keymap"

-- ── Art ───────────────────────────────────────────────────────────────────────

local SPLASH_ART = [==[
{SPLASH_ART}
]==]

local TERMINAL_BANNER = [==[
{TERMINAL_BANNER}
]==]

-- ── Helpers ───────────────────────────────────────────────────────────────────

local function split_lines(s)
  local t = {}
  for l in (s .. "\n"):gmatch("([^\n]*)\n") do
    table.insert(t, (l:gsub("\r", "")))
  end
  while #t > 0 and t[#t]:match("^%s*$") do table.remove(t) end
  while #t > 0 and t[1] :match("^%s*$") do table.remove(t, 1) end
  return t
end

-- ── Override EmptyView.draw ───────────────────────────────────────────────────

local EmptyView = require "core.emptyview"
EmptyView.draw = function(self)
  self:draw_background(style.background)

  local sf  = style.code_font or style.font  -- monospace for art
  local lf  = style.font                      -- proportional for hints
  local dim = style.dim

  -- Bright foreground derived from theme accent
  local acc    = style.accent or { 120, 200, 255, 255 }
  local bright = { acc[1], acc[2], acc[3], 220 }

  -- Drop-shadow: dark, semi-transparent
  local shadow = { 0, 0, 0, 100 }

  -- Shadow offset (scales with DPI)
  local sh = math.ceil(2 * SCALE)

  local art_lines = split_lines(SPLASH_ART)

  -- Line height: slightly tighter for dense block art
  local fh    = math.floor(sf:get_height() * 1.05)
  local art_h = #art_lines * fh

  -- Hint lines
  local hints = {
    { fmt = "%s   run a command",            cmd = "core:find-command" },
    { fmt = "%s   open a file from project", cmd = "core:find-file" },
    { fmt = "%s   change project folder",    cmd = "core:change-project-folder" },
    { fmt = "%s   open a project folder",    cmd = "core:open-project-folder" },
  }
  local hfh     = lf:get_height() + 6
  local hints_h = #hints * hfh + 24

  local total_h = art_h + 24 + hints_h
  local start_y = self.position.y + math.max(style.padding.y, (self.size.y - total_h) / 2)

  -- Measure art width for centering
  local max_art_w = 0
  for _, l in ipairs(art_lines) do
    local w = sf:get_width(l)
    if w > max_art_w then max_art_w = w end
  end
  local art_x = self.position.x + math.max(style.padding.x, (self.size.x - max_art_w) / 2)

  -- Two-pass draw: shadow behind, bright text in front
  local cy = start_y
  for _, l in ipairs(art_lines) do
    renderer.draw_text(sf, l, art_x + sh, cy + sh, shadow)  -- shadow
    renderer.draw_text(sf, l, art_x,      cy,      bright)  -- bright
    cy = cy + fh
  end

  cy = cy + 12

  -- Thin divider
  local div_alpha = { dim[1], dim[2], dim[3], 30 }
  local div_w = self.size.x - style.padding.x * 4
  local div_x = self.position.x + style.padding.x * 2
  renderer.draw_rect(div_x, math.floor(cy), div_w, math.ceil(SCALE), div_alpha)
  cy = cy + 12

  -- Hint lines
  local max_hint_w = 0
  for _, h in ipairs(hints) do
    local binding = keymap.get_binding(h.cmd) or "?"
    local txt = string.format(h.fmt, binding)
    local w = lf:get_width(txt)
    if w > max_hint_w then max_hint_w = w end
  end
  local hx = self.position.x + math.max(style.padding.x, (self.size.x - max_hint_w) / 2)

  for _, h in ipairs(hints) do
    local binding = keymap.get_binding(h.cmd) or "?"
    local txt = string.format(h.fmt, binding)
    renderer.draw_text(lf, txt, hx, cy, dim)
    cy = cy + hfh
  end
end

-- ── Terminal banner on startup ────────────────────────────────────────────────

local _banner_done = false
core.add_thread(function()
  coroutine.yield(1.0)
  if _banner_done then return end
  local function walk(node)
    if not node then return end
    if node.views then
      for _, v in ipairs(node.views) do
        if v.terminal and v.terminal.write then
          v.terminal:write(TERMINAL_BANNER)
          _banner_done = true
        end
      end
    end
    if node.a then walk(node.a) end
    if node.b then walk(node.b) end
  end
  pcall(walk, core.root_view and core.root_view.root_node)
end)
"""

def main():
    lua = LUA \
        .replace("{SPLASH_ART}",      SPLASH_ART) \
        .replace("{TERMINAL_BANNER}", TERMINAL_BANNER)

    os.makedirs(os.path.dirname(OUT_LUA), exist_ok=True)
    with open(OUT_LUA, "w", encoding="utf-8") as f:
        f.write(lua)

    print(f"[OK] Written to: {OUT_LUA}")
    print("\n== Splash Art Preview ==")
    print(SPLASH_ART)
    print("\n== Terminal Banner Preview ==")
    print(TERMINAL_BANNER)

if __name__ == "__main__":
    main()
