#!/usr/bin/env python3
"""
gen_splash_art.py
Generates ASCII art for Lite XL's empty view and terminal splash screen.
Uses pyfiglet for ASCII art generation.
Run this script any time you want to regenerate with different fonts/styles.
"""

import pyfiglet
import os

USERDIR  = os.path.join(os.path.expanduser("~"), ".config", "lite-xl")
OUT_LUA  = os.path.join(USERDIR, "plugins", "splash_art.lua")

# ── Art generation ─────────────────────────────────────────────────────────────

def trim(text):
    lines = [l.rstrip() for l in text.splitlines()]
    while lines and not lines[0].strip():  lines.pop(0)
    while lines and not lines[-1].strip(): lines.pop()
    return lines

def make_splash_art():
    """3D elegant logo for the empty editor view."""
    raw   = pyfiglet.figlet_format("Lite XL", font="larry3d")
    lines = trim(raw)
    width = max(len(l) for l in lines)

    # Add a thin decorative frame
    top  = "  ┌" + "─" * (width + 2) + "┐"
    bot  = "  └" + "─" * (width + 2) + "┘"
    framed = [top]
    for l in lines:
        framed.append("  │ " + l.ljust(width) + " │")
    framed.append(bot)
    return "\n".join(framed)

def make_terminal_banner():
    """Bold colossal banner for the terminal startup."""
    raw   = pyfiglet.figlet_format("Lite XL", font="colossal")
    lines = trim(raw)
    width = max(len(l) for l in lines)

    tagline  = "  The lightweight text editor you will enjoy using."
    divider  = "  " + "═" * (width + 4)
    version_line = "  v" + "2.1.8" + "   |   https://lite-xl.com"

    result = ["", divider]
    for l in lines:
        result.append("   " + l)
    result.append(divider)
    result.append(tagline)
    result.append(version_line)
    result.append(divider)
    result.append("")
    return "\n".join(result)

SPLASH_ART      = make_splash_art()
TERMINAL_BANNER = make_terminal_banner()

# ── Lua plugin template ────────────────────────────────────────────────────────

LUA_TEMPLATE = r"""-- mod-version:3
-- splash_art.lua: Beautiful ASCII art for the empty editor view & terminal startup.
-- Auto-generated by scripts/gen_splash_art.py — re-run the script to regenerate.

local core    = require "core"
local style   = require "core.style"
local keymap  = require "core.keymap"

-- ── Art strings ───────────────────────────────────────────────────────────────

local SPLASH_ART = [==[
{SPLASH_ART}
]==]

local TERMINAL_BANNER = [==[
{TERMINAL_BANNER}
]==]

-- ── Helpers ───────────────────────────────────────────────────────────────────

local function split_lines(s)
  local t = {}
  for l in (s .. "\n"):gmatch("([^\n]*)\n") do
    table.insert(t, l)
  end
  while #t > 0 and t[#t]:match("^%s*$") do table.remove(t) end
  while #t > 0 and t[1]:match("^%s*$")  do table.remove(t, 1) end
  return t
end

-- ── Override EmptyView.draw ───────────────────────────────────────────────────

local EmptyView = require "core.emptyview"
EmptyView.draw = function(self)
  self:draw_background(style.background)

  local sf  = style.code_font or style.font   -- monospace font for art
  local lf  = style.font                       -- ui font for hints
  local dim = style.dim

  local art_lines = split_lines(SPLASH_ART)

  local fh    = math.floor(sf:get_height() * 1.1)
  local art_h = #art_lines * fh

  -- Hint lines
  local hints = {
    { fmt = "%s   run a command",            cmd = "core:find-command" },
    { fmt = "%s   open a file from project", cmd = "core:find-file" },
    { fmt = "%s   change project folder",    cmd = "core:change-project-folder" },
    { fmt = "%s   open a project folder",    cmd = "core:open-project-folder" },
  }
  local hfh     = lf:get_height() + 7
  local hints_h = #hints * hfh + 24

  local total_h  = art_h + 28 + hints_h
  local start_y  = self.position.y + math.max(style.padding.y, (self.size.y - total_h) / 2)

  -- Measure art width
  local max_art_w = 0
  for _, l in ipairs(art_lines) do
    local w = sf:get_width(l)
    if w > max_art_w then max_art_w = w end
  end
  local art_x = self.position.x + math.max(style.padding.x, (self.size.x - max_art_w) / 2)

  -- Draw ASCII logo
  local cy = start_y
  for _, l in ipairs(art_lines) do
    renderer.draw_text(sf, l, art_x, cy, dim)
    cy = cy + fh
  end

  cy = cy + 14

  -- Subtle divider
  local div_alpha = { dim[1], dim[2], dim[3], 35 }
  local div_w = self.size.x - style.padding.x * 4
  local div_x = self.position.x + style.padding.x * 2
  renderer.draw_rect(div_x, math.floor(cy), div_w, math.ceil(SCALE), div_alpha)

  cy = cy + 14

  -- Hint lines
  local max_hint_w = 0
  for _, h in ipairs(hints) do
    local binding = keymap.get_binding(h.cmd) or "?"
    local txt = string.format(h.fmt, binding)
    local w = lf:get_width(txt)
    if w > max_hint_w then max_hint_w = w end
  end
  local hx = self.position.x + math.max(style.padding.x, (self.size.x - max_hint_w) / 2)

  for _, h in ipairs(hints) do
    local binding = keymap.get_binding(h.cmd) or "?"
    local txt = string.format(h.fmt, binding)
    renderer.draw_text(lf, txt, hx, cy, dim)
    cy = cy + hfh
  end
end

-- ── Terminal banner injected once on startup ──────────────────────────────────

local _banner_done = false

core.add_thread(function()
  coroutine.yield(1.0)   -- wait for terminal to initialise
  if _banner_done then return end

  local function walk(node)
    if not node then return end
    if node.views then
      for _, v in ipairs(node.views) do
        if v.terminal and v.terminal.write then
          v.terminal:write(TERMINAL_BANNER)
          _banner_done = true
        end
      end
    end
    if node.a then walk(node.a) end
    if node.b then walk(node.b) end
  end
  pcall(walk, core.root_view and core.root_view.root_node)
end)
"""

# ── Write Lua file ─────────────────────────────────────────────────────────────

def main():
    lua = LUA_TEMPLATE \
        .replace("{SPLASH_ART}",      SPLASH_ART) \
        .replace("{TERMINAL_BANNER}", TERMINAL_BANNER)

    os.makedirs(os.path.dirname(OUT_LUA), exist_ok=True)
    with open(OUT_LUA, "w", encoding="utf-8") as f:
        f.write(lua)

    print(f"[OK] Written to: {OUT_LUA}")
    print("\n== Splash Art (Empty View) ==")
    print(SPLASH_ART)
    print("\n== Terminal Banner ==")
    print(TERMINAL_BANNER)

if __name__ == "__main__":
    main()
